name: Oakhouse WhatsApp Notifier

on:
  schedule:
    - cron: "*/3 * * * *" # cada 3 minutos
  workflow_dispatch: # también lo puedes lanzar manualmente

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          WHATSAPP_TO: ${{ secrets.WHATSAPP_TO }}
          SEARCH_TERM: ${{ secrets.SEARCH_TERM }}
          SCRAPER_ENABLED: ${{ secrets.SCRAPER_ENABLED }}
        run: python main.py
